parameters:
    aws_sdk.config.default:
      version: 'latest'
      region: 'ap-southeast-1'

    aws_sdk.credentials.default:
        credentials:
            key: '%env(AWS_KEY)%'
            secret: '%env(AWS_SECRET)%'

    aws_sdk.credentials.sns:
        credentials:
            key: '%env(AWS_KEY)%'
            secret: '%env(AWS_SECRET)%'